### ISSUE TITLE
panie gdzie muj system zabrales

### ISSUE THREAD

**Issue by boprr** [jakub-swiniarski/LWTE#1]

**Comment by boprr** [comment]
masz maj system oddac

**Comment by jakub-swiniarski** [comment]
Zapewniam pana, iz panski system nie zostal "zabrany" przez moj software. Nie jestem odpowiedzialny za wszelkiego rodzaju wypadki losowe zwiazane z panskim systemem.

**Comment by boprr** [comment]
NIE OBCHODI MI TO SYTM MI ZABRALES
DRANIU
